---
- hosts: 192.168.235.129
  gather_facts: no
  tasks:
    - shell: df -k 
      register: df 
    - debug: var=df.stdout_lines
    - shell: ifconfig
      register: ifconfig
    - debug: var=ifconfig.stdout_lines
    - shell: ps -eo pcpu,user,args | sort -r -k1 | head -n5
      register: ps
    - debug: var=ps.stdout_lines
    - shell: ls -l
      register: ls
    - debug: var=ls.stdout_lines 
